/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class jni_HelloJni */

#ifndef _Included_jni_HelloJni
#define _Included_jni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_HelloJni
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jni_HelloJni_get
  (JNIEnv *, jclass);

/*
 * Class:     jni_HelloJni
 * Method:    set
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jni_HelloJni_set
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
